import React from 'react';
import { LockIcon, SentIcon, ArrowLeft01Icon, Tick01Icon, TickDouble01Icon, Logout01Icon, Attachment01Icon, Location01Icon, Mic01Icon, MicOff01Icon, Video01Icon, VideoOffIcon, CallEnd01Icon, Call02Icon, File01Icon, Download01Icon, Cancel01Icon, Image01Icon, MusicNote01Icon, ArrowRight01Icon, Delete01Icon, Copy01Icon, VolumeHighIcon, Target01Icon, GlobeIcon, UserGroupIcon, MoreHorizontalIcon, PlusSignIcon, ComputerScreenShareIcon, ComputerRemoveIcon, UserAdd01Icon, Sun01Icon, RefreshIcon, MailReply01Icon, PencilEdit01Icon, CropIcon, Moon01Icon } from 'hugeicons-react';

const wrap = (IconComponent) => <IconComponent size={24} strokeWidth={1.8} color="currentColor" />;

export const Icon = {
  lock: wrap(LockIcon),
  send: wrap(SentIcon),
  back: wrap(ArrowLeft01Icon),
  check: wrap(Tick01Icon),
  checkAll: wrap(TickDouble01Icon),
  signout: wrap(Logout01Icon),
  clip: wrap(Attachment01Icon),
  pin: wrap(Location01Icon),
  mic: wrap(Mic01Icon),
  micOff: wrap(MicOff01Icon),
  video: wrap(Video01Icon),
  videoOff: wrap(VideoOffIcon),
  call: wrap(Call02Icon),
  phoneEnd: wrap(CallEnd01Icon),
  file: wrap(File01Icon),
  download: wrap(Download01Icon),
  x: wrap(Cancel01Icon),
  image: wrap(Image01Icon),
  music: wrap(MusicNote01Icon),
  forward: wrap(ArrowRight01Icon),
  trash: wrap(Delete01Icon),
  copy: wrap(Copy01Icon),
  chevronL: wrap(ArrowLeft01Icon),
  chevronR: wrap(ArrowRight01Icon),
  volume: wrap(VolumeHighIcon),
  crosshair: wrap(Target01Icon),
  globe: wrap(GlobeIcon),
  users: wrap(UserGroupIcon),
  dots: wrap(MoreHorizontalIcon),
  plus: wrap(PlusSignIcon),
  monitor: wrap(ComputerScreenShareIcon),
  monitorOff: wrap(ComputerRemoveIcon),
  userPlus: wrap(UserAdd01Icon),
  sun: wrap(Sun01Icon),
  rotate: wrap(RefreshIcon),
  reply: wrap(MailReply01Icon),
  pen: wrap(PencilEdit01Icon),
  crop: wrap(CropIcon),
  moon: wrap(Moon01Icon),
};
